#!/usr/bin/env bash
# Bash script that loops from 1 to 10
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

coun=1
while [ $coun -le 10 ]
do
    if [ $coun -eq 4 ]
    then
        echo "bad Luck"
    elif [ $coun -eq 8 ]
    then
        echo "good Luck"
    else
        echo "Best School"
    fi

    ((coun++))
done
