#!/usr/bin/env bash
# Bash script that loops from 1 to 20
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

coun=1
while [ $coun -le 20 ]
do
    case $coun in
        4)
            echo "$coun and then Bad Luck from China"
            ;;
        9)
            echo "$coun and then Bad Luck from Japan"
            ;;
        17)
            echo "$coun and then Bad Luck from Italy"
            ;;
        *)
            echo $coun
            ;;
    esac

    ((coun++))
done
