#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

heure=0
while [ $heure -le 12 ]
do
    echo "Hour: $heure"
    min=1
    while [ $min -le 59 ]
    do
        echo "$min"
        ((min++))
    done
    ((heure++))
done
