#!/usr/bin/env bash
#< displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

for filena in *; do
    if [[ "$filena" != .* ]]; then
        echo "$filena" | cut -d '-' -f2-
    fi
done
