#!/usr/bin/env bash
# a Bash script that gives you information about the school file

filena="school"

if [ -e "$filena" ]; then
    echo "school file exists"
    if [ -s "$filena" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$filena" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
